-- Kiểm tra dữ liệu đã lưu
-- Service Request Code: 000057337442

-- 1. Kiểm tra Stored Service Request
SELECT 
    ID,
    SERVICE_REQ_CODE,
    PATIENT_NAME,
    CURRENT_ROOM_ID,
    CURRENT_DEPARTMENT_ID,
    STORED_AT,
    STORED_BY
FROM BML_STORED_SERVICE_REQUESTS 
WHERE SERVICE_REQ_CODE = '000057337442';

-- 2. Kiểm tra số lượng Services đã lưu
SELECT 
    COUNT(*) as TOTAL_SERVICES,
    SUM(CASE WHEN IS_CHILD_SERVICE = 0 THEN 1 ELSE 0 END) as PARENT_SERVICES,
    SUM(CASE WHEN IS_CHILD_SERVICE = 1 THEN 1 ELSE 0 END) as CHILD_TESTS
FROM BML_STORED_SR_SERVICES 
WHERE STORED_SERVICE_REQ_ID = (
    SELECT ID FROM BML_STORED_SERVICE_REQUESTS 
    WHERE SERVICE_REQ_CODE = '000057337442'
);

-- 3. Kiểm tra Services và Tests (chi tiết)
SELECT 
    ID,
    IS_CHILD_SERVICE,
    PARENT_SERVICE_ID,
    SERVICE_CODE,
    SERVICE_NAME,
    RECEPTION_CODE,
    SAMPLE_COLL_TIME,
    PRICE
FROM BML_STORED_SR_SERVICES 
WHERE STORED_SERVICE_REQ_ID = (
    SELECT ID FROM BML_STORED_SERVICE_REQUESTS 
    WHERE SERVICE_REQ_CODE = '000057337442'
)
ORDER BY IS_CHILD_SERVICE, SERVICE_CODE;

-- 4. Kiểm tra Workflow đã start chưa
SELECT 
    ID,
    STORED_SERVICE_REQ_ID,
    TO_STATE_ID,
    ACTION_TYPE,
    IS_CURRENT,
    IS_ACTIVE,
    CURR_ROOM_ID,
    CURR_DEPT_ID,
    STARTED_AT,
    ACTION_TIMESTAMP
FROM BML_WORKFLOW_HISTORY 
WHERE STORED_SERVICE_REQ_ID = (
    SELECT ID FROM BML_STORED_SERVICE_REQUESTS 
    WHERE SERVICE_REQ_CODE = '000057337442'
)
AND IS_CURRENT = 1;

-- 5. Kiểm tra Workflow State
SELECT 
    WH.ID,
    WH.TO_STATE_ID,
    WS.STATE_CODE,
    WS.STATE_NAME,
    WS.STATE_ORDER,
    WH.IS_CURRENT,
    WH.IS_ACTIVE
FROM BML_WORKFLOW_HISTORY WH
JOIN BML_WORKFLOW_STATES WS ON WH.TO_STATE_ID = WS.ID
WHERE WH.STORED_SERVICE_REQ_ID = (
    SELECT ID FROM BML_STORED_SERVICE_REQUESTS 
    WHERE SERVICE_REQ_CODE = '000057337442'
)
AND WH.IS_CURRENT = 1;

