-- migrations/007_create_bml_departments_table.sql

CREATE TABLE BML_DEPARTMENTS (
    ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    DEPARTMENT_CODE VARCHAR2(20) NOT NULL UNIQUE,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
    BRANCH_ID VARCHAR2(36) NOT NULL,
    HEAD_OF_DEPARTMENT VARCHAR2(100),
    HEAD_NURSE VARCHAR2(100),
    PARENT_DEPARTMENT_ID VARCHAR2(36),
    SHORT_NAME VARCHAR2(50),
    DEPARTMENT_TYPE_ID VARCHAR2(36) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    SORT_ORDER NUMBER(10,0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER(10,0) DEFAULT 1 NOT NULL
);

-- Comments
COMMENT ON TABLE BML_DEPARTMENTS IS 'Bảng lưu trữ thông tin các khoa/phòng';
COMMENT ON COLUMN BML_DEPARTMENTS.ID IS 'Mã định danh duy nhất';
COMMENT ON COLUMN BML_DEPARTMENTS.DEPARTMENT_CODE IS 'Mã khoa (duy nhất)';
COMMENT ON COLUMN BML_DEPARTMENTS.DEPARTMENT_NAME IS 'Tên khoa';
COMMENT ON COLUMN BML_DEPARTMENTS.BRANCH_ID IS 'ID chi nhánh';
COMMENT ON COLUMN BML_DEPARTMENTS.HEAD_OF_DEPARTMENT IS 'Trưởng khoa';
COMMENT ON COLUMN BML_DEPARTMENTS.HEAD_NURSE IS 'Điều dưỡng trưởng';
COMMENT ON COLUMN BML_DEPARTMENTS.PARENT_DEPARTMENT_ID IS 'ID khoa cha (để tạo cấu trúc phân cấp)';
COMMENT ON COLUMN BML_DEPARTMENTS.SHORT_NAME IS 'Tên viết tắt';
COMMENT ON COLUMN BML_DEPARTMENTS.DEPARTMENT_TYPE_ID IS 'ID loại khoa';
COMMENT ON COLUMN BML_DEPARTMENTS.IS_ACTIVE IS 'Trạng thái hoạt động (1: Hoạt động, 0: Không hoạt động)';
COMMENT ON COLUMN BML_DEPARTMENTS.SORT_ORDER IS 'Thứ tự sắp xếp';
COMMENT ON COLUMN BML_DEPARTMENTS.CREATED_AT IS 'Thời gian tạo bản ghi';
COMMENT ON COLUMN BML_DEPARTMENTS.UPDATED_AT IS 'Thời gian cập nhật cuối cùng';
COMMENT ON COLUMN BML_DEPARTMENTS.DELETED_AT IS 'Thời gian xóa mềm bản ghi';
COMMENT ON COLUMN BML_DEPARTMENTS.CREATED_BY IS 'Người tạo bản ghi';
COMMENT ON COLUMN BML_DEPARTMENTS.UPDATED_BY IS 'Người cập nhật cuối cùng';
COMMENT ON COLUMN BML_DEPARTMENTS.VERSION IS 'Phiên bản của bản ghi';

-- Indexes
CREATE INDEX IDX_BML_DEPT_CODE ON BML_DEPARTMENTS(DEPARTMENT_CODE);
CREATE INDEX IDX_BML_DEPT_NAME ON BML_DEPARTMENTS(DEPARTMENT_NAME);
CREATE INDEX IDX_BML_DEPT_BRANCH ON BML_DEPARTMENTS(BRANCH_ID);
CREATE INDEX IDX_BML_DEPT_TYPE ON BML_DEPARTMENTS(DEPARTMENT_TYPE_ID);
CREATE INDEX IDX_BML_DEPT_PARENT ON BML_DEPARTMENTS(PARENT_DEPARTMENT_ID);
CREATE INDEX IDX_BML_DEPT_ACTIVE ON BML_DEPARTMENTS(IS_ACTIVE);
CREATE INDEX IDX_BML_DEPT_SORT ON BML_DEPARTMENTS(SORT_ORDER);

-- Foreign Key Constraints
ALTER TABLE BML_DEPARTMENTS ADD CONSTRAINT FK_BML_DEPT_BML_BRANCHES 
    FOREIGN KEY (BRANCH_ID) REFERENCES BML_BRANCHES(ID);
ALTER TABLE BML_DEPARTMENTS ADD CONSTRAINT FK_BML_DEPT_BML_DEPT_TYPES 
    FOREIGN KEY (DEPARTMENT_TYPE_ID) REFERENCES BML_DEPARTMENT_TYPES(ID);
ALTER TABLE BML_DEPARTMENTS ADD CONSTRAINT FK_BML_DEPT_BML_DEPT_PARENT 
    FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES BML_DEPARTMENTS(ID);

-- Sample Data
INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Tim Mạch', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Nguyễn Văn A', 'ĐD. Trần Thị B', 'KTM', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 1, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM_PHONG', 'Phòng Tim Mạch', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Nguyễn Văn C', 'ĐD. Trần Thị D', 'KTM_PHONG', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'PHONG'), 1, 2, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Thần Kinh', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Lê Văn E', 'ĐD. Phạm Thị F', 'KTK', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 3, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Ngoại', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Hoàng Văn G', 'ĐD. Vũ Thị H', 'KNG', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 4, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Sản', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Trần Văn I', 'ĐD. Nguyễn Thị J', 'KSN', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 5, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Nhi', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Phạm Văn K', 'ĐD. Lê Thị L', 'KNH', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 6, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Cấp Cứu', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Vũ Văn M', 'ĐD. Hoàng Thị N', 'KCC', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 7, 'system', 'system');

INSERT INTO BML_DEPARTMENTS (ID, DEPARTMENT_CODE, DEPARTMENT_NAME, BRANCH_ID, HEAD_OF_DEPARTMENT, HEAD_NURSE, SHORT_NAME, DEPARTMENT_TYPE_ID, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'KTM', 'Khoa Xét Nghiệm', (SELECT ID FROM BML_BRANCHES WHERE ROWNUM = 1), 'BS. Nguyễn Văn O', 'ĐD. Trần Thị P', 'KXN', (SELECT ID FROM BML_DEPARTMENT_TYPES WHERE TYPE_CODE = 'KHOA'), 1, 8, 'system', 'system');

COMMIT;
