-- migrations/008_create_bml_room_groups_table.sql

CREATE TABLE BML_ROOM_GROUPS (
    ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    ROOM_GROUP_CODE VARCHAR2(20) NOT NULL UNIQUE,
    ROOM_GROUP_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    SORT_ORDER NUMBER(10,0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER(10,0) DEFAULT 1 NOT NULL
);

COMMENT ON TABLE BML_ROOM_GROUPS IS 'Bảng lưu trữ thông tin các nhóm phòng';
COMMENT ON COLUMN BML_ROOM_GROUPS.ID IS 'Mã định danh duy nhất';
COMMENT ON COLUMN BML_ROOM_GROUPS.ROOM_GROUP_CODE IS 'Mã nhóm phòng (duy nhất)';
COMMENT ON COLUMN BML_ROOM_GROUPS.ROOM_GROUP_NAME IS 'Tên nhóm phòng';
COMMENT ON COLUMN BML_ROOM_GROUPS.IS_ACTIVE IS 'Trạng thái hoạt động (1: Hoạt động, 0: Không hoạt động)';
COMMENT ON COLUMN BML_ROOM_GROUPS.SORT_ORDER IS 'Thứ tự sắp xếp';
COMMENT ON COLUMN BML_ROOM_GROUPS.CREATED_AT IS 'Thời gian tạo bản ghi';
COMMENT ON COLUMN BML_ROOM_GROUPS.UPDATED_AT IS 'Thời gian cập nhật cuối cùng';
COMMENT ON COLUMN BML_ROOM_GROUPS.DELETED_AT IS 'Thời gian xóa mềm bản ghi';
COMMENT ON COLUMN BML_ROOM_GROUPS.CREATED_BY IS 'Người tạo bản ghi';
COMMENT ON COLUMN BML_ROOM_GROUPS.UPDATED_BY IS 'Người cập nhật cuối cùng';
COMMENT ON COLUMN BML_ROOM_GROUPS.VERSION IS 'Phiên bản của bản ghi';

-- Indexes
CREATE INDEX IDX_BML_RG_CODE ON BML_ROOM_GROUPS(ROOM_GROUP_CODE);
CREATE INDEX IDX_BML_RG_NAME ON BML_ROOM_GROUPS(ROOM_GROUP_NAME);
CREATE INDEX IDX_BML_RG_ACTIVE ON BML_ROOM_GROUPS(IS_ACTIVE);
CREATE INDEX IDX_BML_RG_SORT ON BML_ROOM_GROUPS(SORT_ORDER);

-- Sample Data
INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'VIP', 'Phòng VIP', 1, 1, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'STANDARD', 'Phòng tiêu chuẩn', 1, 2, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'SHARED', 'Phòng chung', 1, 3, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'ICU', 'Phòng chăm sóc đặc biệt', 1, 4, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'EMERGENCY', 'Phòng cấp cứu', 1, 5, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'SURGERY', 'Phòng phẫu thuật', 1, 6, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'RECOVERY', 'Phòng hồi sức', 1, 7, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'ISOLATION', 'Phòng cách ly', 1, 8, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'MATERNITY', 'Phòng sản phụ', 1, 9, 'system', 'system');

INSERT INTO BML_ROOM_GROUPS (ID, ROOM_GROUP_CODE, ROOM_GROUP_NAME, IS_ACTIVE, SORT_ORDER, CREATED_BY, UPDATED_BY) VALUES
(SYS_GUID(), 'PEDIATRIC', 'Phòng nhi khoa', 1, 10, 'system', 'system');
