-- Migration: 003_create_bml_sample_types_table.sql
-- Create BML_SAMPLE_TYPES table for Sample Type module

-- Drop table if exists
DROP TABLE BML_SAMPLE_TYPES CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BML_SAMPLE_TYPES (
    ID VARCHAR2(36) PRIMARY KEY,
    TYPE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    TYPE_NAME VARCHAR2(200) NOT NULL,
    SHORT_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(2000),
    SORT_ORDER NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1
);

-- Create indexes (Oracle 12c naming constraints - under 30 characters)
CREATE INDEX IDX_BML_SAMPLE_TYPES_CODE ON BML_SAMPLE_TYPES(TYPE_CODE);
CREATE INDEX IDX_BML_SAMPLE_TYPES_NAME ON BML_SAMPLE_TYPES(TYPE_NAME);
CREATE INDEX IDX_BML_SAMPLE_TYPES_ORDER ON BML_SAMPLE_TYPES(SORT_ORDER);
CREATE INDEX IDX_BML_SAMPLE_TYPES_CRT_AT ON BML_SAMPLE_TYPES(CREATED_AT);

-- Insert sample data
INSERT INTO BML_SAMPLE_TYPES (ID, TYPE_CODE, TYPE_NAME, SHORT_NAME, DESCRIPTION, SORT_ORDER) VALUES 
(GENERATE_UUID(), 'BLOOD', 'Mẫu máu', 'Máu', 'Mẫu máu để xét nghiệm', 1);

INSERT INTO BML_SAMPLE_TYPES (ID, TYPE_CODE, TYPE_NAME, SHORT_NAME, DESCRIPTION, SORT_ORDER) VALUES 
(GENERATE_UUID(), 'URINE', 'Mẫu nước tiểu', 'Nước tiểu', 'Mẫu nước tiểu để xét nghiệm', 2);

INSERT INTO BML_SAMPLE_TYPES (ID, TYPE_CODE, TYPE_NAME, SHORT_NAME, DESCRIPTION, SORT_ORDER) VALUES 
(GENERATE_UUID(), 'STOOL', 'Mẫu phân', 'Phân', 'Mẫu phân để xét nghiệm', 3);

INSERT INTO BML_SAMPLE_TYPES (ID, TYPE_CODE, TYPE_NAME, SHORT_NAME, DESCRIPTION, SORT_ORDER) VALUES 
(GENERATE_UUID(), 'SALIVA', 'Mẫu nước bọt', 'Nước bọt', 'Mẫu nước bọt để xét nghiệm', 4);

INSERT INTO BML_SAMPLE_TYPES (ID, TYPE_CODE, TYPE_NAME, SHORT_NAME, DESCRIPTION, SORT_ORDER) VALUES 
(GENERATE_UUID(), 'TISSUE', 'Mẫu mô', 'Mô', 'Mẫu mô sinh thiết', 5);

COMMIT;
