-- Migration: 004_create_bml_sample_receptions_table.sql
-- Create BML_SAMPLE_RECEPTIONS table for Sample Reception module

-- Drop table if exists
DROP TABLE BML_SAMPLE_RECEPTIONS CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BML_SAMPLE_RECEPTIONS (
    ID VARCHAR2(36) PRIMARY KEY,
    RECEPTION_CODE VARCHAR2(50) NOT NULL UNIQUE,
    SAMPLE_TYPE_ID VARCHAR2(36) NOT NULL,
    RECEPTION_DATE DATE NOT NULL,
    SEQUENCE_NUMBER NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1
);

-- Create indexes (Oracle 12c naming constraints - under 30 characters)
CREATE INDEX IDX_BML_SAMPLE_REC_CODE ON BML_SAMPLE_RECEPTIONS(RECEPTION_CODE);
CREATE INDEX IDX_BML_SAMPLE_REC_TYPE ON BML_SAMPLE_RECEPTIONS(SAMPLE_TYPE_ID);
CREATE INDEX IDX_BML_SAMPLE_REC_DATE ON BML_SAMPLE_RECEPTIONS(RECEPTION_DATE);
CREATE INDEX IDX_BML_SAMPLE_REC_SEQ ON BML_SAMPLE_RECEPTIONS(SEQUENCE_NUMBER);
CREATE INDEX IDX_BML_SAMPLE_REC_CRT_AT ON BML_SAMPLE_RECEPTIONS(CREATED_AT);

-- Create foreign key constraint (Oracle 12c naming constraints - under 30 characters)
ALTER TABLE BML_SAMPLE_RECEPTIONS 
ADD CONSTRAINT FK_BML_SAMPLE_REC_SAMPLE_TYPE 
FOREIGN KEY (SAMPLE_TYPE_ID) 
REFERENCES BML_SAMPLE_TYPES(ID);

-- Insert sample data
INSERT INTO BML_SAMPLE_RECEPTIONS (ID, RECEPTION_CODE, SAMPLE_TYPE_ID, RECEPTION_DATE, SEQUENCE_NUMBER) VALUES 
(GENERATE_UUID(), 'BLOOD.20241024.0001', (SELECT ID FROM BML_SAMPLE_TYPES WHERE TYPE_CODE = 'BLOOD' AND ROWNUM = 1), DATE '2024-10-24', 1);

INSERT INTO BML_SAMPLE_RECEPTIONS (ID, RECEPTION_CODE, SAMPLE_TYPE_ID, RECEPTION_DATE, SEQUENCE_NUMBER) VALUES 
(GENERATE_UUID(), 'BLOOD.20241024.0002', (SELECT ID FROM BML_SAMPLE_TYPES WHERE TYPE_CODE = 'BLOOD' AND ROWNUM = 1), DATE '2024-10-24', 2);

INSERT INTO BML_SAMPLE_RECEPTIONS (ID, RECEPTION_CODE, SAMPLE_TYPE_ID, RECEPTION_DATE, SEQUENCE_NUMBER) VALUES 
(GENERATE_UUID(), 'URINE.20241024.0001', (SELECT ID FROM BML_SAMPLE_TYPES WHERE TYPE_CODE = 'URINE' AND ROWNUM = 1), DATE '2024-10-24', 1);

INSERT INTO BML_SAMPLE_RECEPTIONS (ID, RECEPTION_CODE, SAMPLE_TYPE_ID, RECEPTION_DATE, SEQUENCE_NUMBER) VALUES 
(GENERATE_UUID(), 'STOOL.20241024.0001', (SELECT ID FROM BML_SAMPLE_TYPES WHERE TYPE_CODE = 'STOOL' AND ROWNUM = 1), DATE '2024-10-24', 1);

INSERT INTO BML_SAMPLE_RECEPTIONS (ID, RECEPTION_CODE, SAMPLE_TYPE_ID, RECEPTION_DATE, SEQUENCE_NUMBER) VALUES 
(GENERATE_UUID(), 'SALIVA.20241024.0001', (SELECT ID FROM BML_SAMPLE_TYPES WHERE TYPE_CODE = 'SALIVA' AND ROWNUM = 1), DATE '2024-10-24', 1);

COMMIT;
