-- =====================================================
-- Migration: 005_create_bml_patients_table.sql
-- Description: Create BML_PATIENTS table for Patient module
-- Author: LIS GPB Backend
-- Date: 2024-01-15
-- =====================================================

-- Drop table if exists (for clean migration)
DROP TABLE BML_PATIENTS CASCADE CONSTRAINTS;

-- Create BML_PATIENTS table
CREATE TABLE BML_PATIENTS (
    ID VARCHAR2(36) PRIMARY KEY,
    PATIENT_CODE VARCHAR2(50) NOT NULL UNIQUE,
    PATIENT_NAME VARCHAR2(200) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CMND_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    CMND_DATE DATE,
    CMND_PLACE VARCHAR2(200),
    MOBILE VARCHAR2(20),
    PHONE VARCHAR2(20),
    PROVINCE_ID VARCHAR2(36),
    WARD_ID VARCHAR2(36),
    ADDRESS CLOB,
    GENDER_ID VARCHAR2(10),
    GENDER_NAME VARCHAR2(50),
    CAREER_NAME VARCHAR2(200),
    HIS_ID VARCHAR2(50),
    
    -- Base entity fields
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1
);

-- Create indexes for performance
CREATE INDEX IDX_BML_PATIENTS_PATIENT_CODE ON BML_PATIENTS(PATIENT_CODE);
CREATE INDEX IDX_BML_PATIENTS_PATIENT_NAME ON BML_PATIENTS(PATIENT_NAME);
CREATE INDEX IDX_BML_PATIENTS_CMND_NUMBER ON BML_PATIENTS(CMND_NUMBER);
CREATE INDEX IDX_BML_PATIENTS_MOBILE ON BML_PATIENTS(MOBILE);
CREATE INDEX IDX_BML_PATIENTS_PROVINCE_ID ON BML_PATIENTS(PROVINCE_ID);
CREATE INDEX IDX_BML_PATIENTS_WARD_ID ON BML_PATIENTS(WARD_ID);
CREATE INDEX IDX_BML_PATIENTS_GENDER_ID ON BML_PATIENTS(GENDER_ID);
CREATE INDEX IDX_BML_PATIENTS_CREATED_AT ON BML_PATIENTS(CREATED_AT);
CREATE INDEX IDX_BML_PATIENTS_DELETED_AT ON BML_PATIENTS(DELETED_AT);

-- Create foreign key constraints
ALTER TABLE BML_PATIENTS 
ADD CONSTRAINT FK_BML_PATIENTS_PROVINCE 
FOREIGN KEY (PROVINCE_ID) REFERENCES BML_PROVINCES(ID);

ALTER TABLE BML_PATIENTS 
ADD CONSTRAINT FK_BML_PATIENTS_WARD 
FOREIGN KEY (WARD_ID) REFERENCES BML_WARDS(ID);

-- Create check constraints
ALTER TABLE BML_PATIENTS 
ADD CONSTRAINT CK_BML_PATIENTS_GENDER_ID 
CHECK (GENDER_ID IN ('M', 'F', 'OTHER'));

ALTER TABLE BML_PATIENTS 
ADD CONSTRAINT CK_BML_PATIENTS_CMND_LENGTH 
CHECK (LENGTH(CMND_NUMBER) BETWEEN 9 AND 12);

-- Create trigger for updated_at
CREATE OR REPLACE TRIGGER TR_BML_PATIENTS_UPDATE
    BEFORE UPDATE ON BML_PATIENTS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
    :NEW.VERSION := :OLD.VERSION + 1;
END;
/

-- Insert sample data
INSERT INTO BML_PATIENTS (
    ID, PATIENT_CODE, PATIENT_NAME, DATE_OF_BIRTH, CMND_NUMBER, 
    CMND_DATE, CMND_PLACE, MOBILE, PHONE, PROVINCE_ID, WARD_ID, 
    ADDRESS, GENDER_ID, GENDER_NAME, CAREER_NAME, HIS_ID,
    CREATED_BY, UPDATED_BY
) VALUES (
    SYS_GUID(), 'BN202401.0001', 'Nguyễn Văn An', DATE '1990-05-15', '123456789',
    DATE '2010-01-01', 'Công an TP.HCM', '0901234567', '0281234567', 
    (SELECT ID FROM BML_PROVINCES WHERE PROVINCE_CODE = 'SG' AND ROWNUM = 1),
    (SELECT ID FROM BML_WARDS WHERE WARD_CODE = 'Q1W1' AND ROWNUM = 1),
    '123 Đường Lê Lợi, Quận 1, TP.HCM', 'M', 'Nam', 'Kỹ sư phần mềm', 'HIS001',
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1),
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1)
);

INSERT INTO BML_PATIENTS (
    ID, PATIENT_CODE, PATIENT_NAME, DATE_OF_BIRTH, CMND_NUMBER, 
    CMND_DATE, CMND_PLACE, MOBILE, PHONE, PROVINCE_ID, WARD_ID, 
    ADDRESS, GENDER_ID, GENDER_NAME, CAREER_NAME, HIS_ID,
    CREATED_BY, UPDATED_BY
) VALUES (
    SYS_GUID(), 'BN202401.0002', 'Trần Thị Bình', DATE '1985-08-22', '987654321',
    DATE '2012-03-15', 'Công an Hà Nội', '0912345678', '0241234567',
    (SELECT ID FROM BML_PROVINCES WHERE PROVINCE_CODE = 'HN' AND ROWNUM = 1),
    (SELECT ID FROM BML_WARDS WHERE WARD_CODE = 'Q1W2' AND ROWNUM = 1),
    '456 Đường Tràng Tiền, Quận Hoàn Kiếm, Hà Nội', 'F', 'Nữ', 'Bác sĩ', 'HIS002',
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1),
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1)
);

INSERT INTO BML_PATIENTS (
    ID, PATIENT_CODE, PATIENT_NAME, DATE_OF_BIRTH, CMND_NUMBER, 
    CMND_DATE, CMND_PLACE, MOBILE, PHONE, PROVINCE_ID, WARD_ID, 
    ADDRESS, GENDER_ID, GENDER_NAME, CAREER_NAME, HIS_ID,
    CREATED_BY, UPDATED_BY
) VALUES (
    SYS_GUID(), 'BN202401.0003', 'Lê Văn Cường', DATE '1992-12-10', '456789123',
    DATE '2015-06-20', 'Công an Đà Nẵng', '0923456789', '0236123456',
    (SELECT ID FROM BML_PROVINCES WHERE PROVINCE_CODE = 'DN' AND ROWNUM = 1),
    (SELECT ID FROM BML_WARDS WHERE WARD_CODE = 'Q1W3' AND ROWNUM = 1),
    '789 Đường Lê Duẩn, Quận Hải Châu, Đà Nẵng', 'M', 'Nam', 'Y tá', 'HIS003',
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1),
    (SELECT ID FROM BML_USERS WHERE USERNAME = 'admin' AND ROWNUM = 1)
);

-- Commit transaction
COMMIT;

-- Display success message
SELECT 'BML_PATIENTS table created successfully with sample data' AS MESSAGE FROM DUAL;
