-- Migration: Add code generation fields to BML_SAMPLE_TYPES table
-- Date: 2025-10-27
-- Description: Add fields for reception code generation with configurable width and duplicate handling

-- Add new columns to BML_SAMPLE_TYPES table
ALTER TABLE BML_SAMPLE_TYPES ADD (
    CODE_PREFIX VARCHAR2(5) NOT NULL,
    CODE_WIDTH NUMBER(1) DEFAULT 4 NOT NULL,
    ALLOW_DUPLICATE NUMBER(1) DEFAULT 0 NOT NULL,
    RESET_PERIOD VARCHAR2(20) DEFAULT 'MONTHLY' NOT NULL
);

-- Add check constraints
ALTER TABLE BML_SAMPLE_TYPES ADD CONSTRAINT CK_BML_SAMPLE_TYPES_CODE_WIDTH 
    CHECK (CODE_WIDTH >= 1 AND CODE_WIDTH <= 5);

ALTER TABLE BML_SAMPLE_TYPES ADD CONSTRAINT CK_BML_SAMPLE_TYPES_RESET_PERIOD 
    CHECK (RESET_PERIOD IN ('DAILY', 'MONTHLY', 'YEARLY', 'NEVER'));

-- Add indexes for performance
CREATE INDEX IDX_BML_SAMPLE_TYPES_CODE_PREFIX ON BML_SAMPLE_TYPES(CODE_PREFIX);
CREATE INDEX IDX_BML_SAMPLE_TYPES_RESET_PERIOD ON BML_SAMPLE_TYPES(RESET_PERIOD);

-- Update existing sample types with default values
UPDATE BML_SAMPLE_TYPES SET 
    CODE_PREFIX = UPPER(SUBSTR(TYPE_CODE, 1, 5)),
    CODE_WIDTH = 4,
    ALLOW_DUPLICATE = 0,
    RESET_PERIOD = 'MONTHLY'
WHERE CODE_PREFIX IS NULL;

-- Add comments
COMMENT ON COLUMN BML_SAMPLE_TYPES.CODE_PREFIX IS 'Tiền tố cho mã tiếp nhận (1-5 ký tự)';
COMMENT ON COLUMN BML_SAMPLE_TYPES.CODE_WIDTH IS 'Độ rộng phần số trong mã tiếp nhận (1-5)';
COMMENT ON COLUMN BML_SAMPLE_TYPES.ALLOW_DUPLICATE IS 'Cho phép mã tiếp nhận trùng lặp (0=No, 1=Yes)';
COMMENT ON COLUMN BML_SAMPLE_TYPES.RESET_PERIOD IS 'Chu kỳ reset số thứ tự (DAILY/MONTHLY/YEARLY/NEVER)';

-- Verify the changes
SELECT 
    TYPE_CODE,
    TYPE_NAME,
    CODE_PREFIX,
    CODE_WIDTH,
    ALLOW_DUPLICATE,
    RESET_PERIOD
FROM BML_SAMPLE_TYPES
ORDER BY SORT_ORDER;

PROMPT 'Code generation fields added to BML_SAMPLE_TYPES table successfully!';
