-- Migration: 008_create_bml_service_groups_table.sql
-- Tạo bảng BML_SERVICE_GROUPS cho module Service Group

-- Tạo bảng BML_SERVICE_GROUPS
CREATE TABLE BML_SERVICE_GROUPS (
    ID UUID PRIMARY KEY DEFAULT SYS_GUID(),
    SERVICE_GROUP_CODE VARCHAR2(20) NOT NULL UNIQUE,
    SERVICE_GROUP_NAME VARCHAR2(100) NOT NULL,
    SHORT_NAME VARCHAR2(50),
    MAPPING VARCHAR2(2000),
    DESCRIPTION CLOB,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    SORT_ORDER NUMBER(10) DEFAULT 0,
    ICON VARCHAR2(100),
    COLOR VARCHAR2(7),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1
);

-- Tạo indexes (tên ngắn hơn 30 ký tự)
CREATE INDEX IDX_BML_SG_CODE ON BML_SERVICE_GROUPS(SERVICE_GROUP_CODE);
CREATE INDEX IDX_BML_SG_NAME ON BML_SERVICE_GROUPS(SERVICE_GROUP_NAME);
CREATE INDEX IDX_BML_SG_ACTIVE ON BML_SERVICE_GROUPS(IS_ACTIVE);
CREATE INDEX IDX_BML_SG_SORT ON BML_SERVICE_GROUPS(SORT_ORDER);
CREATE INDEX IDX_BML_SG_SHORT_NAME ON BML_SERVICE_GROUPS(SHORT_NAME);

-- Thêm check constraints (tên ngắn hơn 30 ký tự)
ALTER TABLE BML_SERVICE_GROUPS ADD CONSTRAINT CK_BML_SG_ACTIVE
    CHECK (IS_ACTIVE IN (0, 1));

ALTER TABLE BML_SERVICE_GROUPS ADD CONSTRAINT CK_BML_SG_COLOR
    CHECK (COLOR IS NULL OR REGEXP_LIKE(COLOR, '^#[0-9A-Fa-f]{6}$'));

ALTER TABLE BML_SERVICE_GROUPS ADD CONSTRAINT CK_BML_SG_SORT_ORDER
    CHECK (SORT_ORDER >= 0);

-- Thêm comments
COMMENT ON TABLE BML_SERVICE_GROUPS IS 'Bảng quản lý nhóm dịch vụ';
COMMENT ON COLUMN BML_SERVICE_GROUPS.SERVICE_GROUP_CODE IS 'Mã nhóm dịch vụ (unique)';
COMMENT ON COLUMN BML_SERVICE_GROUPS.SERVICE_GROUP_NAME IS 'Tên nhóm dịch vụ';
COMMENT ON COLUMN BML_SERVICE_GROUPS.SHORT_NAME IS 'Tên viết tắt';
COMMENT ON COLUMN BML_SERVICE_GROUPS.MAPPING IS 'Mapping với hệ thống khác (JSON)';
COMMENT ON COLUMN BML_SERVICE_GROUPS.DESCRIPTION IS 'Mô tả chi tiết';
COMMENT ON COLUMN BML_SERVICE_GROUPS.IS_ACTIVE IS 'Trạng thái hoạt động (0=Inactive, 1=Active)';
COMMENT ON COLUMN BML_SERVICE_GROUPS.SORT_ORDER IS 'Thứ tự sắp xếp';
COMMENT ON COLUMN BML_SERVICE_GROUPS.ICON IS 'Icon cho UI';
COMMENT ON COLUMN BML_SERVICE_GROUPS.COLOR IS 'Màu sắc cho UI (hex code)';

-- Thêm dữ liệu mẫu
INSERT INTO BML_SERVICE_GROUPS (ID, SERVICE_GROUP_CODE, SERVICE_GROUP_NAME, SHORT_NAME, DESCRIPTION, IS_ACTIVE, SORT_ORDER, ICON, COLOR) VALUES
(SYS_GUID(), 'LAB', 'Xét nghiệm', 'XN', 'Nhóm dịch vụ xét nghiệm cơ bản và chuyên sâu', 1, 1, 'lab-icon', '#FF5722'),
(SYS_GUID(), 'RADIO', 'Chẩn đoán hình ảnh', 'CĐHA', 'Nhóm dịch vụ chẩn đoán hình ảnh', 1, 2, 'radio-icon', '#2196F3'),
(SYS_GUID(), 'SURGERY', 'Phẫu thuật', 'PT', 'Nhóm dịch vụ phẫu thuật', 1, 3, 'surgery-icon', '#4CAF50'),
(SYS_GUID(), 'EMERGENCY', 'Cấp cứu', 'CC', 'Nhóm dịch vụ cấp cứu', 1, 4, 'emergency-icon', '#F44336'),
(SYS_GUID(), 'PHARMACY', 'Dược', 'DƯỢC', 'Nhóm dịch vụ dược phẩm', 1, 5, 'pharmacy-icon', '#9C27B0');

-- Commit changes
COMMIT;

-- Log completion
SELECT 'Service Groups table created successfully' AS status FROM DUAL;
