-- Create BML_PROFILES table
CREATE TABLE BML_PROFILES (
    ID VARCHAR2(36) PRIMARY KEY DEFAULT SYS_GUID(),
    USER_ID VARCHAR2(36) NOT NULL UNIQUE,
    PROVINCE_ID VARCHAR2(36),
    WARD_ID VARCHAR2(36),
    ADDRESS VARCHAR2(500),
    DEPARTMENT_ID VARCHAR2(36),
    POSITION VARCHAR2(100),
    EMPLOYEE_CODE VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(10),
    AVATAR VARCHAR2(500),
    MAPPED_USERNAME VARCHAR2(100),
    MAPPED_PASSWORD VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1 NOT NULL
);

-- Foreign Keys (shortened names for Oracle 12c 30-character limit)
ALTER TABLE BML_PROFILES ADD CONSTRAINT FK_BML_PROF_USR 
    FOREIGN KEY (USER_ID) REFERENCES BML_USERS(ID);
ALTER TABLE BML_PROFILES ADD CONSTRAINT FK_BML_PROF_PRV 
    FOREIGN KEY (PROVINCE_ID) REFERENCES BML_PROVINCES(ID);
ALTER TABLE BML_PROFILES ADD CONSTRAINT FK_BML_PROF_WRD 
    FOREIGN KEY (WARD_ID) REFERENCES BML_WARDS(ID);
ALTER TABLE BML_PROFILES ADD CONSTRAINT FK_BML_PROF_DEP 
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES BML_DEPARTMENTS(ID);

-- Indexes (shortened names for Oracle 12c 30-character limit)
CREATE INDEX IDX_BML_PROF_USR ON BML_PROFILES(USER_ID);
CREATE INDEX IDX_BML_PROF_EMP ON BML_PROFILES(EMPLOYEE_CODE);
CREATE INDEX IDX_BML_PROF_PHN ON BML_PROFILES(PHONE_NUMBER);
CREATE INDEX IDX_BML_PROF_PRV ON BML_PROFILES(PROVINCE_ID);
CREATE INDEX IDX_BML_PROF_WRD ON BML_PROFILES(WARD_ID);
CREATE INDEX IDX_BML_PROF_DEP ON BML_PROFILES(DEPARTMENT_ID);

-- Check constraints (shortened names for Oracle 12c 30-character limit)
ALTER TABLE BML_PROFILES ADD CONSTRAINT CK_BML_PROF_GEN 
    CHECK (GENDER IS NULL OR GENDER IN ('MALE', 'FEMALE', 'OTHER'));

-- Comments for table and columns
COMMENT ON TABLE BML_PROFILES IS 'BẢNG QUẢN LÝ THÔNG TIN CHI TIẾT NGƯỜI DÙNG';
COMMENT ON COLUMN BML_PROFILES.ID IS 'Unique identifier for the profile';
COMMENT ON COLUMN BML_PROFILES.USER_ID IS 'ID người dùng';
COMMENT ON COLUMN BML_PROFILES.PROVINCE_ID IS 'ID tỉnh/thành phố';
COMMENT ON COLUMN BML_PROFILES.WARD_ID IS 'ID xã/phường';
COMMENT ON COLUMN BML_PROFILES.ADDRESS IS 'Địa chỉ chi tiết';
COMMENT ON COLUMN BML_PROFILES.DEPARTMENT_ID IS 'ID khoa/phòng ban';
COMMENT ON COLUMN BML_PROFILES.POSITION IS 'Chức vụ';
COMMENT ON COLUMN BML_PROFILES.EMPLOYEE_CODE IS 'Mã nhân viên';
COMMENT ON COLUMN BML_PROFILES.PHONE_NUMBER IS 'Số điện thoại';
COMMENT ON COLUMN BML_PROFILES.DATE_OF_BIRTH IS 'Ngày sinh';
COMMENT ON COLUMN BML_PROFILES.GENDER IS 'Giới tính';
COMMENT ON COLUMN BML_PROFILES.AVATAR IS 'URL ảnh đại diện';
COMMENT ON COLUMN BML_PROFILES.MAPPED_USERNAME IS 'Username cho hệ thống tích hợp';
COMMENT ON COLUMN BML_PROFILES.MAPPED_PASSWORD IS 'Password cho hệ thống tích hợp';
COMMENT ON COLUMN BML_PROFILES.CREATED_AT IS 'Timestamp when the record was created';
COMMENT ON COLUMN BML_PROFILES.UPDATED_AT IS 'Timestamp when the record was last updated';
COMMENT ON COLUMN BML_PROFILES.DELETED_AT IS 'Timestamp when the record was soft-deleted';
COMMENT ON COLUMN BML_PROFILES.CREATED_BY IS 'ID of the user who created the record';
COMMENT ON COLUMN BML_PROFILES.UPDATED_BY IS 'ID of the user who last updated the record';
COMMENT ON COLUMN BML_PROFILES.VERSION IS 'Version number for optimistic locking';
