-- database/migrations/010_create_user_rooms_table.sql
-- Tạo bảng phân quyền phòng cho user

-- Drop table if exists
DROP TABLE BML_USER_ROOMS CASCADE CONSTRAINTS;

-- Create table
CREATE TABLE BML_USER_ROOMS (
    ID VARCHAR2(36) PRIMARY KEY DEFAULT SYS_GUID(),
    USER_ID VARCHAR2(36) NOT NULL,
    ROOM_ID VARCHAR2(36) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(36),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1
);

-- Foreign Keys
ALTER TABLE BML_USER_ROOMS ADD CONSTRAINT FK_UR_USER
    FOREIGN KEY (USER_ID) REFERENCES BML_USERS(ID);
ALTER TABLE BML_USER_ROOMS ADD CONSTRAINT FK_UR_ROOM
    FOREIGN KEY (ROOM_ID) REFERENCES BML_ROOMS(ID);

-- Unique constraint
ALTER TABLE BML_USER_ROOMS ADD CONSTRAINT UK_UR_USER_ROOM
    UNIQUE (USER_ID, ROOM_ID);

-- Indexes
CREATE INDEX IDX_UR_USER ON BML_USER_ROOMS(USER_ID);
CREATE INDEX IDX_UR_ROOM ON BML_USER_ROOMS(ROOM_ID);
CREATE INDEX IDX_UR_ACTIVE ON BML_USER_ROOMS(IS_ACTIVE);

-- Comments
COMMENT ON TABLE BML_USER_ROOMS IS 'BẢNG PHÂN QUYỀN PHÒNG CHO USER';
COMMENT ON COLUMN BML_USER_ROOMS.ID IS 'UNIQUE IDENTIFIER FOR THE USER ROOM';
COMMENT ON COLUMN BML_USER_ROOMS.USER_ID IS 'ID NGƯỜI DÙNG';
COMMENT ON COLUMN BML_USER_ROOMS.ROOM_ID IS 'ID PHÒNG';
COMMENT ON COLUMN BML_USER_ROOMS.IS_ACTIVE IS 'TRẠNG THÁI HOẠT ĐỘNG';
COMMENT ON COLUMN BML_USER_ROOMS.CREATED_AT IS 'TIMESTAMP WHEN THE RECORD WAS CREATED';
COMMENT ON COLUMN BML_USER_ROOMS.UPDATED_AT IS 'TIMESTAMP WHEN THE RECORD WAS LAST UPDATED';
COMMENT ON COLUMN BML_USER_ROOMS.CREATED_BY IS 'ID OF THE USER WHO CREATED THE RECORD';
COMMENT ON COLUMN BML_USER_ROOMS.UPDATED_BY IS 'ID OF THE USER WHO LAST UPDATED THE RECORD';
COMMENT ON COLUMN BML_USER_ROOMS.VERSION IS 'VERSION NUMBER FOR OPTIMISTIC LOCKING';
