-- database/migrations/012_create_bml_services_table.sql
-- Tạo bảng BML_SERVICES cho module Dịch vụ

-- Tạo bảng BML_SERVICES
CREATE TABLE BML_SERVICES (
    ID VARCHAR2(36) PRIMARY KEY DEFAULT SYS_GUID(),
    SERVICE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    SERVICE_NAME VARCHAR2(200) NOT NULL,
    SHORT_NAME VARCHAR2(100),
    SERVICE_GROUP_ID VARCHAR2(36) NOT NULL,
    UNIT_OF_MEASURE_ID VARCHAR2(36),
    MAPPING CLOB,
    NUM_ORDER NUMBER DEFAULT 0,
    CURRENT_PRICE NUMBER(15,2) DEFAULT 0,
    PARENT_SERVICE_ID VARCHAR2(36),
    DESCRIPTION CLOB,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    VERSION NUMBER DEFAULT 1,
    
    CONSTRAINT FK_SERVICES_GROUP 
        FOREIGN KEY (SERVICE_GROUP_ID) 
        REFERENCES BML_SERVICE_GROUPS(ID),
    CONSTRAINT FK_SERVICES_PARENT 
        FOREIGN KEY (PARENT_SERVICE_ID) 
        REFERENCES BML_SERVICES(ID)
);

-- Tạo indexes
CREATE INDEX IDX_SERVICES_CODE ON BML_SERVICES(SERVICE_CODE);
CREATE INDEX IDX_SERVICES_GROUP ON BML_SERVICES(SERVICE_GROUP_ID);
CREATE INDEX IDX_SERVICES_PARENT ON BML_SERVICES(PARENT_SERVICE_ID);
CREATE INDEX IDX_SERVICES_ORDER ON BML_SERVICES(NUM_ORDER);
CREATE INDEX IDX_SERVICES_PRICE ON BML_SERVICES(CURRENT_PRICE);
CREATE INDEX IDX_SERVICES_ACTIVE ON BML_SERVICES(IS_ACTIVE);
CREATE INDEX IDX_SERVICES_DELETED ON BML_SERVICES(DELETED_AT);

-- Thêm comments
COMMENT ON TABLE BML_SERVICES IS 'BẢNG DỊCH VỤ Y TẾ';
COMMENT ON COLUMN BML_SERVICES.SERVICE_CODE IS 'MÃ DỊCH VỤ';
COMMENT ON COLUMN BML_SERVICES.SERVICE_NAME IS 'TÊN DỊCH VỤ';
COMMENT ON COLUMN BML_SERVICES.SHORT_NAME IS 'TÊN VIẾT TẮT';
COMMENT ON COLUMN BML_SERVICES.SERVICE_GROUP_ID IS 'ID NHÓM DỊCH VỤ';
COMMENT ON COLUMN BML_SERVICES.UNIT_OF_MEASURE_ID IS 'ID ĐƠN VỊ TÍNH';
COMMENT ON COLUMN BML_SERVICES.MAPPING IS 'MAPPING JSON CHO TÍCH HỢP';
COMMENT ON COLUMN BML_SERVICES.NUM_ORDER IS 'THỨ TỰ SẮP XẾP';
COMMENT ON COLUMN BML_SERVICES.CURRENT_PRICE IS 'GIÁ HIỆN TẠI';
COMMENT ON COLUMN BML_SERVICES.PARENT_SERVICE_ID IS 'ID DỊCH VỤ CHA';
COMMENT ON COLUMN BML_SERVICES.DESCRIPTION IS 'MÔ TẢ CHI TIẾT';
COMMENT ON COLUMN BML_SERVICES.IS_ACTIVE IS 'TRẠNG THÁI HOẠT ĐỘNG';

-- Thêm dữ liệu mẫu
INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC001', 'Xét nghiệm máu tổng quát', 'XNMTQ', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'XN' LIMIT 1), 1, 150000, 'Xét nghiệm máu tổng quát bao gồm các chỉ số cơ bản', 1, 'admin', 'admin');

INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, PARENT_SERVICE_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC001-01', 'Công thức máu', 'CTM', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'XN' LIMIT 1), (SELECT ID FROM BML_SERVICES WHERE SERVICE_CODE = 'SVC001' LIMIT 1), 1, 50000, 'Xét nghiệm công thức máu', 1, 'admin', 'admin');

INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, PARENT_SERVICE_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC001-02', 'Sinh hóa máu', 'SHM', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'XN' LIMIT 1), (SELECT ID FROM BML_SERVICES WHERE SERVICE_CODE = 'SVC001' LIMIT 1), 2, 80000, 'Xét nghiệm sinh hóa máu', 1, 'admin', 'admin');

INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC002', 'Chẩn đoán hình ảnh', 'CDHA', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'CDHA' LIMIT 1), 2, 200000, 'Chẩn đoán hình ảnh tổng quát', 1, 'admin', 'admin');

INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, PARENT_SERVICE_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC002-01', 'X-quang ngực', 'XQN', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'CDHA' LIMIT 1), (SELECT ID FROM BML_SERVICES WHERE SERVICE_CODE = 'SVC002' LIMIT 1), 1, 80000, 'X-quang ngực thẳng', 1, 'admin', 'admin');

INSERT INTO BML_SERVICES (ID, SERVICE_CODE, SERVICE_NAME, SHORT_NAME, SERVICE_GROUP_ID, PARENT_SERVICE_ID, NUM_ORDER, CURRENT_PRICE, DESCRIPTION, IS_ACTIVE, CREATED_BY, UPDATED_BY) 
VALUES (SYS_GUID(), 'SVC002-02', 'CT ngực', 'CTN', (SELECT ID FROM BML_SERVICE_GROUPS WHERE SERVICE_GROUP_CODE = 'CDHA' LIMIT 1), (SELECT ID FROM BML_SERVICES WHERE SERVICE_CODE = 'SVC002' LIMIT 1), 2, 300000, 'CT scan ngực', 1, 'admin', 'admin');

PROMPT 'Bảng BML_SERVICES đã được tạo thành công với dữ liệu mẫu!';
