CREATE TABLE BML_UNITS_OF_MEASURE (
    ID VARCHAR2(36) PRIMARY KEY,
    UNIT_OF_MEASURE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    UNIT_OF_MEASURE_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    MAPPING CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1
);

CREATE INDEX IDX_BML_UOM_CODE ON BML_UNITS_OF_MEASURE(UNIT_OF_MEASURE_CODE);
CREATE INDEX IDX_BML_UOM_NAME ON BML_UNITS_OF_MEASURE(UNIT_OF_MEASURE_NAME);


