-- Migration: Create BML_WORKFLOW_STATES table
-- Description: Tạo bảng lưu trữ các trạng thái trong workflow (Master Data)

-- Drop table if exists (for clean migration)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BML_WORKFLOW_STATES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Create table
CREATE TABLE BML_WORKFLOW_STATES (
    ID VARCHAR2(36) PRIMARY KEY DEFAULT SYS_GUID(),
    STATE_CODE VARCHAR2(50) NOT NULL,
    STATE_NAME VARCHAR2(200) NOT NULL,
    STATE_DESCRIPTION VARCHAR2(1000),
    STATE_ORDER NUMBER NOT NULL,
    CAN_SKIP NUMBER(1) DEFAULT 0,
    REQUIRES_APPROVAL NUMBER(1) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    
    -- Base Entity fields
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1,
    
    CONSTRAINT UK_WF_STATE_CODE UNIQUE (STATE_CODE)
);

-- Indexes
CREATE INDEX IDX_WF_STATES_CODE ON BML_WORKFLOW_STATES(STATE_CODE);
CREATE INDEX IDX_WF_STATES_ORDER ON BML_WORKFLOW_STATES(STATE_ORDER);
CREATE INDEX IDX_WF_STATES_ACTIVE ON BML_WORKFLOW_STATES(IS_ACTIVE);
CREATE INDEX IDX_WF_STATES_DELETED ON BML_WORKFLOW_STATES(DELETED_AT);

-- Comments
COMMENT ON TABLE BML_WORKFLOW_STATES IS 'Bảng lưu trữ các trạng thái trong workflow (Master Data)';
COMMENT ON COLUMN BML_WORKFLOW_STATES.STATE_CODE IS 'Mã trạng thái (unique)';
COMMENT ON COLUMN BML_WORKFLOW_STATES.STATE_NAME IS 'Tên trạng thái';
COMMENT ON COLUMN BML_WORKFLOW_STATES.STATE_DESCRIPTION IS 'Mô tả chi tiết trạng thái';
COMMENT ON COLUMN BML_WORKFLOW_STATES.STATE_ORDER IS 'Thứ tự trong workflow (1, 2, 3...)';
COMMENT ON COLUMN BML_WORKFLOW_STATES.CAN_SKIP IS 'Có thể bỏ qua không (0 = không, 1 = có)';
COMMENT ON COLUMN BML_WORKFLOW_STATES.REQUIRES_APPROVAL IS 'Cần phê duyệt không (0 = không, 1 = có)';
COMMENT ON COLUMN BML_WORKFLOW_STATES.IS_ACTIVE IS 'Trạng thái active/inactive';

-- Insert sample data (7 default states)
INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'SAMPLE_COLLECTION', 'Lấy mẫu', 'Bước lấy mẫu từ bệnh nhân', 1, 0, 0, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'SAMPLE_HANDOVER', 'Bàn giao mẫu', 'Bàn giao mẫu từ phòng lấy mẫu đến phòng xét nghiệm', 2, 0, 0, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'SAMPLE_SEPARATION', 'Tách mẫu', 'Tách mẫu thành các phần nhỏ để xử lý', 3, 0, 0, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'MACHINE_RUNNING', 'Chạy máy', 'Chạy máy xét nghiệm', 4, 0, 0, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'RESULT_EVALUATION', 'Đánh giá kết quả', 'Đánh giá và xác nhận kết quả', 5, 0, 1, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'RESULT_APPROVAL', 'Phê duyệt kết quả', 'Phê duyệt kết quả bởi bác sĩ', 6, 0, 1, 1, 'system'
);

INSERT INTO BML_WORKFLOW_STATES (
    ID, STATE_CODE, STATE_NAME, STATE_DESCRIPTION, STATE_ORDER, CAN_SKIP, REQUIRES_APPROVAL, IS_ACTIVE, CREATED_BY
) VALUES (
    SYS_GUID(), 'COMPLETED', 'Hoàn thành', 'Hoàn thành quy trình', 7, 0, 0, 1, 'system'
);

COMMIT;

