-- Migration: Create BML_STORED_SERVICE_REQUESTS table
-- Description: Lưu thông tin Service Request từ HIS vào LIS database

-- Drop table if exists (for clean migration)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BML_STORED_SERVICE_REQUESTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Create table
CREATE TABLE BML_STORED_SERVICE_REQUESTS (
    -- ID và References
    ID VARCHAR2(36) PRIMARY KEY DEFAULT SYS_GUID(),
    HIS_SERVICE_REQ_CODE VARCHAR2(50) NOT NULL,
    HIS_SERVICE_REQ_ID NUMBER,
    
    -- Service Request Info
    SERVICE_REQ_CODE VARCHAR2(50) NOT NULL,
    SERVICE_REQ_STT_ID NUMBER,
    SERVICE_REQ_STT_CODE VARCHAR2(10),
    SERVICE_REQ_TYPE_ID NUMBER,
    SERVICE_REQ_TYPE_CODE VARCHAR2(10),
    INSTRUCTION_TIME NUMBER,
    INSTRUCTION_DATE NUMBER,
    ICD_CODE VARCHAR2(20),
    ICD_NAME VARCHAR2(500),
    ICD_SUB_CODE VARCHAR2(20),
    ICD_TEXT VARCHAR2(1000),
    TREATMENT_ID NUMBER,
    TREATMENT_CODE VARCHAR2(50),
    NOTE VARCHAR2(1000),
    
    -- Request Location
    REQUEST_ROOM_ID NUMBER,
    REQUEST_ROOM_CODE VARCHAR2(50),
    REQUEST_ROOM_NAME VARCHAR2(200),
    REQUEST_ROOM_LIS_ID VARCHAR2(36),
    REQUEST_DEPARTMENT_ID NUMBER,
    REQUEST_DEPARTMENT_CODE VARCHAR2(50),
    REQUEST_DEPARTMENT_NAME VARCHAR2(200),
    REQUEST_DEPARTMENT_LIS_ID VARCHAR2(36),
    
    -- Execute Location
    EXECUTE_ROOM_ID NUMBER,
    EXECUTE_ROOM_CODE VARCHAR2(50),
    EXECUTE_ROOM_NAME VARCHAR2(200),
    EXECUTE_ROOM_LIS_ID VARCHAR2(36),
    EXECUTE_DEPARTMENT_ID NUMBER,
    EXECUTE_DEPARTMENT_CODE VARCHAR2(50),
    EXECUTE_DEPARTMENT_NAME VARCHAR2(200),
    EXECUTE_DEPARTMENT_LIS_ID VARCHAR2(36),
    
    -- Patient Info
    PATIENT_ID NUMBER,
    PATIENT_CODE VARCHAR2(50),
    PATIENT_NAME VARCHAR2(200),
    PATIENT_DOB NUMBER,
    PATIENT_CMND_NUMBER VARCHAR2(20),
    PATIENT_CMND_DATE NUMBER,
    PATIENT_CMND_PLACE VARCHAR2(200),
    PATIENT_MOBILE VARCHAR2(20),
    PATIENT_PHONE VARCHAR2(20),
    PATIENT_PROVINCE_CODE VARCHAR2(10),
    PATIENT_PROVINCE_NAME VARCHAR2(200),
    PATIENT_PROVINCE_LIS_ID VARCHAR2(36),
    PATIENT_COMMUNE_CODE VARCHAR2(20),
    PATIENT_COMMUNE_NAME VARCHAR2(200),
    PATIENT_COMMUNE_LIS_ID VARCHAR2(36),
    PATIENT_ADDRESS VARCHAR2(500),
    PATIENT_GENDER_ID NUMBER,
    PATIENT_GENDER_NAME VARCHAR2(50),
    PATIENT_CAREER_NAME VARCHAR2(200),
    PATIENT_LIS_ID VARCHAR2(36),
    
    -- Context When Storing (NEW)
    CURRENT_ROOM_ID VARCHAR2(36),           -- ID phòng user đang làm việc
    CURRENT_DEPARTMENT_ID VARCHAR2(36),     -- ID khoa user đang làm việc
    
    -- Metadata
    RAW_RESPONSE_JSON CLOB,
    STORED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STORED_BY VARCHAR2(50),
    
    -- Base Entity
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1,
    
    CONSTRAINT UK_STORED_SR_CODE UNIQUE (SERVICE_REQ_CODE)
);

-- Indexes
CREATE INDEX IDX_SSR_CODE ON BML_STORED_SERVICE_REQUESTS(SERVICE_REQ_CODE);
CREATE INDEX IDX_SSR_HIS_CODE ON BML_STORED_SERVICE_REQUESTS(HIS_SERVICE_REQ_CODE);
CREATE INDEX IDX_SSR_STORED_AT ON BML_STORED_SERVICE_REQUESTS(STORED_AT);
CREATE INDEX IDX_SSR_PATIENT_CODE ON BML_STORED_SERVICE_REQUESTS(PATIENT_CODE);
CREATE INDEX IDX_SSR_CURR_ROOM ON BML_STORED_SERVICE_REQUESTS(CURRENT_ROOM_ID);
CREATE INDEX IDX_SSR_CURR_DEPT ON BML_STORED_SERVICE_REQUESTS(CURRENT_DEPARTMENT_ID);

-- Comments
COMMENT ON TABLE BML_STORED_SERVICE_REQUESTS IS 'Bảng lưu trữ Service Request từ HIS vào LIS';
COMMENT ON COLUMN BML_STORED_SERVICE_REQUESTS.CURRENT_ROOM_ID IS 'ID phòng user đang làm việc khi lưu Service Request';
COMMENT ON COLUMN BML_STORED_SERVICE_REQUESTS.CURRENT_DEPARTMENT_ID IS 'ID khoa user đang làm việc khi lưu Service Request';

COMMIT;

