-- Migration: Create BML_STORED_SR_SERVICES table (rút ngắn tên để phù hợp Oracle 30 ký tự)
-- Description: Lưu cả parent services và child tests trong một bảng (quan hệ cha-con)

-- Drop table if exists (for clean migration)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BML_STORED_SR_SERVICES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Create table
CREATE TABLE BML_STORED_SR_SERVICES (
    ID VARCHAR2(36) PRIMARY KEY,
    STORED_SERVICE_REQ_ID VARCHAR2(36) NOT NULL,
    PARENT_SERVICE_ID VARCHAR2(36),
    
    -- HIS Service Info
    HIS_SERE_SERV_ID NUMBER,
    SERVICE_ID NUMBER,
    SERVICE_CODE VARCHAR2(50),
    SERVICE_NAME VARCHAR2(200),
    PRICE NUMBER(15,2),
    
    -- LIS Service Info
    LIS_SERVICE_ID VARCHAR2(36),
    UOM_ID VARCHAR2(36),                     -- Unit of Measure ID (rút ngắn)
    UOM_CODE VARCHAR2(50),                    -- Unit of Measure Code (rút ngắn)
    UOM_NAME VARCHAR2(200),                  -- Unit of Measure Name (rút ngắn)
    
    -- Additional fields
    RANGE_TEXT VARCHAR2(500),
    RANGE_LOW NUMBER(15,2),
    RANGE_HIGH NUMBER(15,2),
    MAPPING CLOB,
    TEST_ORDER NUMBER,
    SHORT_NAME VARCHAR2(100),
    DESCRIPTION CLOB,
    RESULT_TEXT CLOB, -- Kết quả xét nghiệm (3-5 trang A4)
    
    -- Sample Collection Info (NEW)
    RECEPTION_CODE VARCHAR2(50),             -- Mã tiếp nhận mẫu
    SAMPLE_COLL_TIME TIMESTAMP,              -- Thời gian lấy mẫu (rút ngắn)
    COLLECTED_BY_USER_ID VARCHAR2(36),       -- ID user lấy mẫu (optional)
    
    -- Child-specific fields (chỉ có giá trị khi PARENT_SERVICE_ID IS NOT NULL)
    TEST_ID VARCHAR2(36),
    IS_ACTIVE NUMBER(1),
    TEST_CREATED_AT TIMESTAMP,
    TEST_UPDATED_AT TIMESTAMP,
    TEST_CREATED_BY VARCHAR2(50),
    TEST_UPDATED_BY VARCHAR2(50),
    TEST_VERSION NUMBER,
    
    -- Service Type Flag
    IS_CHILD_SERVICE NUMBER(1) DEFAULT 0, -- 0 = parent, 1 = child
    
    -- Base Entity
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1,
    
    CONSTRAINT FK_SSR_SERV_REQ FOREIGN KEY (STORED_SERVICE_REQ_ID) 
        REFERENCES BML_STORED_SERVICE_REQUESTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SSR_SERV_PARENT FOREIGN KEY (PARENT_SERVICE_ID) 
        REFERENCES BML_STORED_SR_SERVICES(ID) ON DELETE CASCADE
);

-- Indexes (rút ngắn tên để phù hợp Oracle 30 ký tự)
CREATE INDEX IDX_SSR_SERV_REQ ON BML_STORED_SR_SERVICES(STORED_SERVICE_REQ_ID);
CREATE INDEX IDX_SSR_SERV_PARENT ON BML_STORED_SR_SERVICES(PARENT_SERVICE_ID);
CREATE INDEX IDX_SSR_SERV_CHILD ON BML_STORED_SR_SERVICES(IS_CHILD_SERVICE);
CREATE INDEX IDX_SSR_SERV_CODE ON BML_STORED_SR_SERVICES(SERVICE_CODE);
CREATE INDEX IDX_SSR_SERV_LIS_ID ON BML_STORED_SR_SERVICES(LIS_SERVICE_ID);
CREATE INDEX IDX_SSR_SERV_REC ON BML_STORED_SR_SERVICES(RECEPTION_CODE);
CREATE INDEX IDX_SSR_SERV_TIME ON BML_STORED_SR_SERVICES(SAMPLE_COLL_TIME);
CREATE INDEX IDX_SSR_SERV_USER ON BML_STORED_SR_SERVICES(COLLECTED_BY_USER_ID);

-- Comments
COMMENT ON TABLE BML_STORED_SR_SERVICES IS 'Bảng lưu parent services và child tests (quan hệ cha-con)';
COMMENT ON COLUMN BML_STORED_SR_SERVICES.IS_CHILD_SERVICE IS '0 = parent service, 1 = child test';
COMMENT ON COLUMN BML_STORED_SR_SERVICES.RECEPTION_CODE IS 'Mã tiếp nhận mẫu';
COMMENT ON COLUMN BML_STORED_SR_SERVICES.SAMPLE_COLL_TIME IS 'Thời gian lấy mẫu';
COMMENT ON COLUMN BML_STORED_SR_SERVICES.COLLECTED_BY_USER_ID IS 'ID user thực hiện lấy mẫu';

COMMIT;

