-- Migration: 001_create_his_service_requests_table.sql
-- Create HIS Service Requests table

-- Drop table if exists
DROP TABLE HSR_SERVICE_REQUESTS CASCADE CONSTRAINTS;

-- Create HSR_SERVICE_REQUESTS table
CREATE TABLE HSR_SERVICE_REQUESTS (
    ID NUMBER PRIMARY KEY,
    SERVICE_REQ_CODE VARCHAR2(50) NOT NULL UNIQUE,
    SERVICE_REQ_STT_ID NUMBER NOT NULL,
    SERVICE_REQ_STT_CODE VARCHAR2(10) NOT NULL,
    SERVICE_REQ_TYPE_ID NUMBER NOT NULL,
    SERVICE_REQ_TYPE_CODE VARCHAR2(10) NOT NULL,
    INSTRUCTION_TIME NUMBER NOT NULL,
    INSTRUCTION_DATE NUMBER NOT NULL,
    ICD_CODE VARCHAR2(20),
    ICD_NAME VARCHAR2(500),
    ICD_SUB_CODE VARCHAR2(20),
    ICD_TEXT VARCHAR2(1000),
    TREATMENT_ID NUMBER NOT NULL,
    TREATMENT_CODE VARCHAR2(50) NOT NULL,
    NOTE VARCHAR2(1000),
    
    -- Request Location
    REQUEST_ROOM_ID NUMBER NOT NULL,
    REQUEST_ROOM_CODE VARCHAR2(50) NOT NULL,
    REQUEST_ROOM_NAME VARCHAR2(200) NOT NULL,
    REQUEST_DEPARTMENT_ID NUMBER NOT NULL,
    REQUEST_DEPARTMENT_CODE VARCHAR2(50) NOT NULL,
    REQUEST_DEPARTMENT_NAME VARCHAR2(200) NOT NULL,
    
    -- Execute Location
    EXECUTE_ROOM_ID NUMBER NOT NULL,
    EXECUTE_ROOM_CODE VARCHAR2(50) NOT NULL,
    EXECUTE_ROOM_NAME VARCHAR2(200) NOT NULL,
    EXECUTE_DEPARTMENT_ID NUMBER NOT NULL,
    EXECUTE_DEPARTMENT_CODE VARCHAR2(50) NOT NULL,
    EXECUTE_DEPARTMENT_NAME VARCHAR2(200) NOT NULL,
    
    -- Patient Info
    PATIENT_ID NUMBER NOT NULL,
    PATIENT_CODE VARCHAR2(50) NOT NULL,
    PATIENT_NAME VARCHAR2(200) NOT NULL,
    PATIENT_DOB NUMBER NOT NULL,
    PATIENT_CMND_NUMBER VARCHAR2(20),
    PATIENT_CMND_DATE NUMBER,
    PATIENT_CMND_PLACE VARCHAR2(200),
    PATIENT_MOBILE VARCHAR2(20),
    PATIENT_PHONE VARCHAR2(20),
    PATIENT_PROVINCE_ID NUMBER,
    PATIENT_PROVINCE_CODE VARCHAR2(10),
    PATIENT_PROVINCE_NAME VARCHAR2(200),
    PATIENT_WARD_ID NUMBER,
    PATIENT_COMMUNE_CODE VARCHAR2(20),
    PATIENT_COMMUNE_NAME VARCHAR2(200),
    PATIENT_ADDRESS VARCHAR2(500),
    PATIENT_GENDER_ID NUMBER NOT NULL,
    PATIENT_GENDER_NAME VARCHAR2(50) NOT NULL,
    PATIENT_CAREER_NAME VARCHAR2(200),
    PATIENT_LIS_ID VARCHAR2(50)
);

-- Create indexes
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_CODE ON HSR_SERVICE_REQUESTS(SERVICE_REQ_CODE);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_PATIENT_ID ON HSR_SERVICE_REQUESTS(PATIENT_ID);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_PATIENT_CODE ON HSR_SERVICE_REQUESTS(PATIENT_CODE);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_INSTRUCTION_DATE ON HSR_SERVICE_REQUESTS(INSTRUCTION_DATE);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_STATUS ON HSR_SERVICE_REQUESTS(SERVICE_REQ_STT_ID);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_TYPE ON HSR_SERVICE_REQUESTS(SERVICE_REQ_TYPE_ID);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_REQUEST_DEPT ON HSR_SERVICE_REQUESTS(REQUEST_DEPARTMENT_ID);
CREATE INDEX IDX_HSR_SERVICE_REQUESTS_EXECUTE_DEPT ON HSR_SERVICE_REQUESTS(EXECUTE_DEPARTMENT_ID);

-- Add comments
COMMENT ON TABLE HSR_SERVICE_REQUESTS IS 'Bảng yêu cầu dịch vụ từ HIS';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.ID IS 'ID yêu cầu dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.SERVICE_REQ_CODE IS 'Mã yêu cầu dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.SERVICE_REQ_STT_ID IS 'ID trạng thái yêu cầu';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.SERVICE_REQ_STT_CODE IS 'Mã trạng thái yêu cầu';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.SERVICE_REQ_TYPE_ID IS 'ID loại yêu cầu';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.SERVICE_REQ_TYPE_CODE IS 'Mã loại yêu cầu';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.INSTRUCTION_TIME IS 'Thời gian chỉ định';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.INSTRUCTION_DATE IS 'Ngày chỉ định';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.ICD_CODE IS 'Mã ICD';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.ICD_NAME IS 'Tên ICD';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.TREATMENT_ID IS 'ID điều trị';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.TREATMENT_CODE IS 'Mã điều trị';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_ID IS 'ID bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_CODE IS 'Mã bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_NAME IS 'Tên bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_DOB IS 'Ngày sinh bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_GENDER_ID IS 'ID giới tính bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_GENDER_NAME IS 'Tên giới tính bệnh nhân';
COMMENT ON COLUMN HSR_SERVICE_REQUESTS.PATIENT_LIS_ID IS 'ID bệnh nhân trong LIS';
