-- Migration: 002_create_his_service_request_details_table.sql
-- Create HIS Service Request Details table

-- Drop table if exists
DROP TABLE HSR_SERVICE_REQUEST_DETAILS CASCADE CONSTRAINTS;

-- Create HSR_SERVICE_REQUEST_DETAILS table
CREATE TABLE HSR_SERVICE_REQUEST_DETAILS (
    HIS_SERE_SERV_ID NUMBER PRIMARY KEY,
    SERVICE_REQUEST_ID NUMBER NOT NULL,
    SERVICE_ID NUMBER NOT NULL,
    SERVICE_CODE VARCHAR2(50) NOT NULL,
    SERVICE_NAME VARCHAR2(500) NOT NULL,
    PRICE NUMBER(15,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    EXECUTE_TIME NUMBER,
    RESULT VARCHAR2(1000),
    NOTE VARCHAR2(1000),
    
    -- LIS Service Mapping (Optional)
    LIS_SERVICE_ID VARCHAR2(50),
    LIS_SERVICE_CODE VARCHAR2(50),
    LIS_SERVICE_NAME VARCHAR2(500),
    LIS_SERVICE_SHORT_NAME VARCHAR2(100),
    LIS_SERVICE_PRICE NUMBER(15,2),
    LIS_SERVICE_GROUP_ID VARCHAR2(50),
    LIS_SERVICE_GROUP_NAME VARCHAR2(200),
    LIS_UNIT_OF_MEASURE_ID VARCHAR2(50),
    LIS_UNIT_OF_MEASURE_NAME VARCHAR2(100),
    LIS_MAPPING CLOB,
    LIS_IS_ACTIVE NUMBER DEFAULT 1
);

-- Create indexes
CREATE INDEX IDX_HSR_SERVICE_DETAILS_REQ_ID ON HSR_SERVICE_REQUEST_DETAILS(SERVICE_REQUEST_ID);
CREATE INDEX IDX_HSR_SERVICE_DETAILS_SERVICE_ID ON HSR_SERVICE_REQUEST_DETAILS(SERVICE_ID);
CREATE INDEX IDX_HSR_SERVICE_DETAILS_SERVICE_CODE ON HSR_SERVICE_REQUEST_DETAILS(SERVICE_CODE);
CREATE INDEX IDX_HSR_SERVICE_DETAILS_STATUS ON HSR_SERVICE_REQUEST_DETAILS(STATUS);
CREATE INDEX IDX_HSR_SERVICE_DETAILS_LIS_ID ON HSR_SERVICE_REQUEST_DETAILS(LIS_SERVICE_ID);

-- Add foreign key constraint
ALTER TABLE HSR_SERVICE_REQUEST_DETAILS 
ADD CONSTRAINT FK_HSR_DETAILS_REQ 
FOREIGN KEY (SERVICE_REQUEST_ID) 
REFERENCES HSR_SERVICE_REQUESTS(ID);

-- Add comments
COMMENT ON TABLE HSR_SERVICE_REQUEST_DETAILS IS 'Bảng chi tiết dịch vụ yêu cầu từ HIS';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.HIS_SERE_SERV_ID IS 'ID chi tiết dịch vụ HIS';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.SERVICE_REQUEST_ID IS 'ID yêu cầu dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.SERVICE_ID IS 'ID dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.SERVICE_CODE IS 'Mã dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.SERVICE_NAME IS 'Tên dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.PRICE IS 'Giá dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.STATUS IS 'Trạng thái';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.LIS_SERVICE_ID IS 'ID dịch vụ LIS';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.LIS_SERVICE_CODE IS 'Mã dịch vụ LIS';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.LIS_SERVICE_NAME IS 'Tên dịch vụ LIS';
COMMENT ON COLUMN HSR_SERVICE_REQUEST_DETAILS.LIS_MAPPING IS 'Mapping JSON với LIS';
