-- Migration: 003_create_his_service_tests_table.sql
-- Create HIS Service Tests table

-- Drop table if exists
DROP TABLE HSR_SERVICE_TESTS CASCADE CONSTRAINTS;

-- Create HSR_SERVICE_TESTS table
CREATE TABLE HSR_SERVICE_TESTS (
    ID VARCHAR2(50) PRIMARY KEY,
    SERVICE_REQUEST_DETAIL_ID NUMBER NOT NULL,
    TEST_CODE VARCHAR2(50) NOT NULL,
    TEST_NAME VARCHAR2(500) NOT NULL,
    SHORT_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(1000),
    UNIT_OF_MEASURE_ID VARCHAR2(50),
    UNIT_OF_MEASURE_NAME VARCHAR2(100),
    RANGE_TEXT VARCHAR2(500),
    RANGE_LOW NUMBER(10,2),
    RANGE_HIGH NUMBER(10,2),
    MAPPING CLOB,
    TEST_ORDER NUMBER DEFAULT 1,
    PRICE NUMBER(15,2) DEFAULT 0,
    IS_ACTIVE NUMBER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1
);

-- Create indexes
CREATE INDEX IDX_HSR_SERVICE_TESTS_DETAIL_ID ON HSR_SERVICE_TESTS(SERVICE_REQUEST_DETAIL_ID);
CREATE INDEX IDX_HSR_SERVICE_TESTS_CODE ON HSR_SERVICE_TESTS(TEST_CODE);
CREATE INDEX IDX_HSR_SERVICE_TESTS_ORDER ON HSR_SERVICE_TESTS(TEST_ORDER);
CREATE INDEX IDX_HSR_SERVICE_TESTS_ACTIVE ON HSR_SERVICE_TESTS(IS_ACTIVE);

-- Add foreign key constraint
ALTER TABLE HSR_SERVICE_TESTS 
ADD CONSTRAINT FK_HSR_TESTS_DETAIL 
FOREIGN KEY (SERVICE_REQUEST_DETAIL_ID) 
REFERENCES HSR_SERVICE_REQUEST_DETAILS(HIS_SERE_SERV_ID);

-- Add comments
COMMENT ON TABLE HSR_SERVICE_TESTS IS 'Bảng xét nghiệm chi tiết từ HIS';
COMMENT ON COLUMN HSR_SERVICE_TESTS.ID IS 'ID xét nghiệm';
COMMENT ON COLUMN HSR_SERVICE_TESTS.SERVICE_REQUEST_DETAIL_ID IS 'ID chi tiết dịch vụ';
COMMENT ON COLUMN HSR_SERVICE_TESTS.TEST_CODE IS 'Mã xét nghiệm';
COMMENT ON COLUMN HSR_SERVICE_TESTS.TEST_NAME IS 'Tên xét nghiệm';
COMMENT ON COLUMN HSR_SERVICE_TESTS.SHORT_NAME IS 'Tên viết tắt';
COMMENT ON COLUMN HSR_SERVICE_TESTS.DESCRIPTION IS 'Mô tả';
COMMENT ON COLUMN HSR_SERVICE_TESTS.UNIT_OF_MEASURE_ID IS 'ID đơn vị tính';
COMMENT ON COLUMN HSR_SERVICE_TESTS.UNIT_OF_MEASURE_NAME IS 'Tên đơn vị tính';
COMMENT ON COLUMN HSR_SERVICE_TESTS.RANGE_TEXT IS 'Khoảng giá trị';
COMMENT ON COLUMN HSR_SERVICE_TESTS.RANGE_LOW IS 'Giá trị thấp nhất';
COMMENT ON COLUMN HSR_SERVICE_TESTS.RANGE_HIGH IS 'Giá trị cao nhất';
COMMENT ON COLUMN HSR_SERVICE_TESTS.MAPPING IS 'Mapping JSON';
COMMENT ON COLUMN HSR_SERVICE_TESTS.TEST_ORDER IS 'Thứ tự xét nghiệm';
COMMENT ON COLUMN HSR_SERVICE_TESTS.PRICE IS 'Giá xét nghiệm';
COMMENT ON COLUMN HSR_SERVICE_TESTS.IS_ACTIVE IS 'Trạng thái hoạt động';
